author: Othman Alikhan
url: https://othmanalikhan.github.io # root address of the site

permalink: /:slug

favicon: "favicon.ico"

twitter:
    username: AlikhanOthman
    card: summary_large_image

#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  back_home_text: "home.." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description
  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  show_copyright: true # show copyright notice in footer

navbar_entries:
  - title: Home
    url: /
  - title: Portfolio
    url: portfolio
  - title: Articles
    url: articles
  - title: About
    url: about

footer_entries:
  - title: Linkedin
    url: https://www.linkedin.com/in/othmanalikhan
  - title: Github
    url: https://github.com/OthmanAlikhan
  - title: Upwork
    url: https://www.upwork.com/freelancers/~013852999aef755af1
  - title: Feed
    url: feed.xml

soopr:
  publish_token: "" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

google_analytics: G-DT1F8NTN97
